/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import Controleur.cltClient;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author benndui
 */

public class Choisissez extends javax.swing.JFrame {

    /**
     * Creates new form Choisissez
     */
    private cltClient clt;
    public Choisissez() throws SQLException {
        initComponents();
        clt = new cltClient();
        if(cltClient.isSource()){
            clt.creeComboModel(clt.getRapDAO().getTousRapportUser(cltClient.getVis().getVis_id()), jComboBox1);
        }else{
            clt.creeComboModel(clt.getRapDAO().getRapportUser3Ans(cltClient.getVis().getVis_id()), jComboBox1);
        }  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        exitBtn = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        validatedBtn = new javax.swing.JLabel();
        clipboard = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitBtn.setFont(new java.awt.Font("Galvji", 1, 13)); // NOI18N
        exitBtn.setForeground(new java.awt.Color(255, 93, 94));
        exitBtn.setText("X");
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnMouseClicked(evt);
            }
        });
        mainPanel.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sélectionner un rapport" }));
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        mainPanel.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 130, -1));

        validatedBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn_validated.png"))); // NOI18N
        validatedBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                validatedBtnMouseClicked(evt);
            }
        });
        mainPanel.add(validatedBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 120, 40));

        clipboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clipBoard#1.png"))); // NOI18N
        mainPanel.add(clipboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gsbFinaleBig.png"))); // NOI18N
        logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoMouseClicked(evt);
            }
        });
        mainPanel.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background#1.png"))); // NOI18N
        mainPanel.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBtnMouseClicked

    private void logoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        try {
            new GSBapplication().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Choisissez.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_logoMouseClicked

    private void validatedBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_validatedBtnMouseClicked
        try {
            clt.selectRapport(jComboBox1);
            if(cltClient.isSource()){
                 this.setVisible(false);
                 new Modifier().setVisible(true);
            }else{
                 this.setVisible(false);
                 new Consulter().setVisible(true);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Choisissez.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_validatedBtnMouseClicked

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        
    }//GEN-LAST:event_jComboBox1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Choisissez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Choisissez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Choisissez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Choisissez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Choisissez().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Choisissez.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel clipboard;
    private javax.swing.JLabel exitBtn;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel validatedBtn;
    // End of variables declaration//GEN-END:variables
}
