/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

/**
 *
 * @author benndui
 */
public class Choisissez extends javax.swing.JFrame {

    /**
     * Creates new form Choisissez
     */
    public Choisissez() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        exitBtn = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        consulter = new javax.swing.JCheckBox();
        editLabel = new javax.swing.JLabel();
        consLabel = new javax.swing.JLabel();
        modifier = new javax.swing.JCheckBox();
        clipboard = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitBtn.setFont(new java.awt.Font("Galvji", 1, 13)); // NOI18N
        exitBtn.setForeground(new java.awt.Color(255, 93, 94));
        exitBtn.setText("X");
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnMouseClicked(evt);
            }
        });
        mainPanel.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        mainPanel.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 140, -1));
        mainPanel.add(consulter, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, -1, -1));

        editLabel.setText("Modifier");
        mainPanel.add(editLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, -1, -1));

        consLabel.setText("Consulter");
        mainPanel.add(consLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, -1, -1));
        mainPanel.add(modifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, -1, -1));

        clipboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/clipBoard#1.png"))); // NOI18N
        mainPanel.add(clipboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/gsbFinaleBig.png"))); // NOI18N
        mainPanel.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/background#1.png"))); // NOI18N
        mainPanel.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Choisissez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Choisissez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Choisissez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Choisissez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Choisissez().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel clipboard;
    private javax.swing.JLabel consLabel;
    private javax.swing.JCheckBox consulter;
    private javax.swing.JLabel editLabel;
    private javax.swing.JLabel exitBtn;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JCheckBox modifier;
    // End of variables declaration//GEN-END:variables
}
